# Generated by Django 3.0.8 on 2020-09-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitarif_user', '0005_auto_20200903_1820'),
        ('recipe', '0003_auto_20200801_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitarif_user.BitarifUser'),
        ),
    ]
