USER_NOT_FOUND_TEXT = "User not found by giving firebase id"
CATEGORY_NOT_FOUND_TEXT = "Category not found"
DIFFICULTY_NOT_FOUND_TEXT = "Difficulty not found"
INGREDIENT_NOT_FOUND_TEXT = "Ingredient not found"
SUCCESSFUL_TEXT = "Successful"
MISSING_PARAMS = "Missing parameters"
SOMETHING_WENT_WRONG = "Something went wrong. Please try again"
AUTH_FAILED = "Authentication failed"
