# Generated by Django 3.0.8 on 2020-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
