# Generated by Django 3.0.8 on 2020-07-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitarifUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(max_length=400, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Adress')),
                ('name', models.CharField(blank=True, default='bitarif User', max_length=100, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ManyToManyField(related_name='followers', to='bitarif_user.BitarifUser')),
            ],
        ),
    ]
