# Generated by Django 3.0.8 on 2020-08-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitarif_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitarifuser',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='bitarif_user.BitarifUser'),
        ),
    ]
