# Generated by Django 3.0.8 on 2020-08-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitarif_user', '0002_auto_20200803_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitarifuser',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followers', to='bitarif_user.BitarifUser'),
        ),
    ]
