# Generated by Django 3.0.8 on 2020-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitarif_user', '0004_bitarifuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitarifuser',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
