# Generated by Django 3.0.8 on 2020-09-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitarif_user', '0005_auto_20200903_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitarifuser',
            name='profile_pic',
            field=models.CharField(default='https://www.tenforums.com/geek/gars/images/2/types/thumb_15951118880user.png', max_length=500),
        ),
    ]
