# Generated by Django 3.0.8 on 2020-09-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitarif_user', '0006_auto_20200921_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitarifuser',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
